version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    container_name: foodgram-db
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    container_name: foodgram-backend
    image: greenpandorik/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    container_name: foodgram-front
    image: greenpandorik/foodgram-frontend:latest
    volumes:
     - ../frontend/:/app/result_build/
    depends_on:
        - db

  nginx:
    container_name: foodgram-nginx
    restart: always
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
      - frontend