# Generated by Django 3.2 on 2023-06-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('id',), 'verbose_name': 'Теги', 'verbose_name_plural': 'Теги'},
        ),
    ]
